import { useState, useCallback } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { Sparkles, Save, Play, ArrowLeft, Loader2, HelpCircle } from 'lucide-react';
import AppShell from '../../components/AppShell';
import ProtectedRoute from '../../components/ProtectedRoute';
import useWorkflowStore from '../../store/workflowStore';
import api from '../../lib/axios';

export default function WorkflowBuilder() {
  const router = useRouter();
  const { generateWorkflow, saveWorkflow, isLoading, error, clearError } = useWorkflowStore();
  const [prompt, setPrompt] = useState('');
  const [generatedWf, setGeneratedWf] = useState(null);
  const [wfName, setWfName] = useState('');
  const [wfDesc, setWfDesc] = useState('');

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!prompt.trim()) return;
    clearError();
    const result = await generateWorkflow(prompt);
    if (result.success) {
      setGeneratedWf(result.workflow);
      setWfName(result.workflow.name);
      setWfDesc(result.workflow.description);
    }
  };

  const handleSave = async () => {
    if (!generatedWf) return;
    const finalWorkflow = {
      ...generatedWf,
      name: wfName,
      description: wfDesc,
    };
    const result = await saveWorkflow(finalWorkflow);
    if (result.success) {
      const id = result.workflow.id || result.workflow._id;
      router.push(`/workflows/${id}`);
    }
  };

  return (
    <ProtectedRoute>
      <Head>
        <title>AI Workflow Generator — Agentflow AI</title>
      </Head>
      <AppShell>
        <div style={{ maxWidth: 800, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          <div>
            <h1 style={{ fontFamily: 'Space Grotesk, sans-serif', fontSize: '1.5rem', fontWeight: 700, marginBottom: '0.25rem' }}>
              AI Workflow Generator
            </h1>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.875rem' }}>
              Describe your automation in plain English. Our AI will construct a visual node graph instantly.
            </p>
          </div>

          {/* Prompt panel */}
          <div className="glass-card" style={{ padding: '1.5rem' }}>
            <form onSubmit={handleGenerate} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div>
                <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', fontWeight: 500, display: 'block', marginBottom: '0.4rem' }}>
                  Automation Prompt
                </label>
                <textarea
                  className="input-field"
                  style={{ minHeight: 100, resize: 'vertical' }}
                  placeholder="e.g., When I receive a new invoice, classify it using AI. If it is approved, send an email to the customer and post a Slack message. Otherwise, send a Slack message to #finance."
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  disabled={isLoading}
                />
              </div>

              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                  <HelpCircle size={13} /> Uses OpenRouter or Gemini fallback
                </span>
                <button className="btn-primary" type="submit" disabled={isLoading || !prompt.trim()}>
                  {isLoading ? (
                    <>
                      <Loader2 size={15} className="animate-spin" /> Generating Graph...
                    </>
                  ) : (
                    <>
                      <Sparkles size={15} /> Generate Workflow
                    </>
                  )}
                </button>
              </div>
            </form>
          </div>

          {error && (
            <div style={{ background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.25)', color: '#fca5a5', padding: '1rem', borderRadius: 10, fontSize: '0.875rem' }}>
              Error: {error}
            </div>
          )}

          {/* Preview & config */}
          {generatedWf && (
            <div className="glass-card slide-in" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--border)', paddingBottom: '0.75rem' }}>
                <span style={{ fontWeight: 600, fontSize: '1rem' }}>Generated Workflow Preview</span>
                <span className="badge badge-success" style={{ textTransform: 'uppercase' }}>
                  Generated by {generatedWf._generatedBy || 'AI'}
                </span>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                <div>
                  <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', fontWeight: 500, display: 'block', marginBottom: '0.4rem' }}>
                    Workflow Name
                  </label>
                  <input
                    className="input-field"
                    value={wfName}
                    onChange={(e) => setWfName(e.target.value)}
                  />
                </div>
                <div>
                  <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', fontWeight: 500, display: 'block', marginBottom: '0.4rem' }}>
                    Description
                  </label>
                  <input
                    className="input-field"
                    value={wfDesc}
                    onChange={(e) => setWfDesc(e.target.value)}
                  />
                </div>
              </div>

              {/* Node summary list */}
              <div>
                <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', fontWeight: 500, display: 'block', marginBottom: '0.5rem' }}>
                  Generated Steps ({generatedWf.nodes?.length || 0})
                </label>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                  {generatedWf.nodes?.map((node, i) => (
                    <div key={node.id} style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', padding: '0.6rem 0.8rem', background: 'var(--surface-3)', borderRadius: 8, border: '1px solid var(--border)' }}>
                      <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', fontWeight: 600 }}>#{i+1}</span>
                      <span className="badge" style={{ background: 'rgba(99,102,241,0.1)', color: '#a5b4fc', fontSize: '0.7rem' }}>
                        {node.data?.type || 'node'}
                      </span>
                      <span style={{ fontSize: '0.85rem', fontWeight: 500 }}>{node.data?.label}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div style={{ display: 'flex', gap: '0.75rem', justifyContent: 'flex-end', marginTop: '0.5rem' }}>
                <button className="btn-ghost" onClick={() => setGeneratedWf(null)}>
                  Clear
                </button>
                <button className="btn-primary" onClick={handleSave}>
                  <Save size={15} /> Save & Open Canvas
                </button>
              </div>
            </div>
          )}
        </div>
      </AppShell>
    </ProtectedRoute>
  );
}
